spring:
  mail:
    username: // 개발자 gmail
    password: // 개발자 본인의 앱 비밀번호
  
  data:
    redis:
      host: localhost  # 로컬 실행 시 localhost 사용
      port: 6379
      password: password  # docker-compose.yml의 Redis 비밀번호
      database: 0

